gymMembership/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('about/', views.about, name='about'),

    path('classes/', views.classes, name='classes'),
    path('classes/<int:class_id>/', views.class_detail, name='detail'),

    path('membership/create/', views.MembershipCreate.as_view(), name='membership_create'),
    path('membership/<int:user_id>/', views.membership, name='membership'),
    path('membership/<int:pk>/update/', views.MembershipUpdate.as_view(), name='membership_update'),
    path('membership/<int:membership_id>/assoc_class/<int:class_id>/', views.assoc_class, name='assoc_class'),
    path('membership/<int:membership_id>/unassoc_class/<int:class_id>/', views.unassoc_class, name='unassoc_class'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.conf import settings

# Create your models here.

Locations = (
    ('M', 'Muharraq'),
    ('S', 'Seef')
)

class Class(models.Model):
    name = models.CharField(max_length=100)
    code = models.IntegerField()
    trainer = models.CharField(max_length=100)
    location = models.CharField(
        max_length=1,
        choices=Locations,
        default=Locations[0][0]
    )
    start_date = models.DateField('Start Date')
    end_date = models.DateField('End Date')
    days = ArrayField(models.CharField(max_length=100), size = 2)
    time = models.TimeField('Start Time')
    duration = models.CharField(max_length=100)
    seats = models.IntegerField('Total Seats')

    def __str__(self):
        return self.name

class Membership(models.Model):
    location = models.CharField(
        max_length=1,
        choices=Locations,
        default=Locations[0][0]
    )
    start_date = models.DateField('Start Date')
    end_date = models.DateField('End Date')
    user_code = models.IntegerField(default=0, blank=True)
    credit = models.IntegerField(default=0, blank=True)
    image = models.CharField(max_length=800, default='image not available', blank=True)

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        primary_key=True,
    )

    classes = models.ManyToManyField(Class, blank=True)

main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Membership, Class

from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

def home(request):
  return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def classes(request):
    classes_list = Class.objects.all()

    return render(request, 'classes/index.html', {
        'classes': classes_list
    })

@login_required
def class_detail(request, class_id):
    return HttpResponse('<h1>Class Details</h1>')

@login_required
def assoc_class(request, membership_id, class_id):
  Membership.objects.get(user_id=membership_id).classes.add(class_id)
  one_class = Class.objects.get(id=class_id)
  one_class.seats -= 1
  one_class.save()

  return redirect('membership', user_id=membership_id)

@login_required
def unassoc_class(request, membership_id, class_id):
  Membership.objects.get(user_id=membership_id).classes.remove(class_id)
  one_class = Class.objects.get(id=class_id)
  one_class.seats += 1
  one_class.save()

  return redirect('membership', user_id=membership_id)

@login_required
def membership(request, user_id):
    try:
        classes_list = Membership.objects.get(user_id=user_id).classes.all()
        membership = Membership.objects.get(user_id=user_id)
        return render(request, 'membership/index.html', {
            'membership': membership,
            'classes': classes_list
            })
    except:
        return redirect('membership_create')

class MembershipCreate(CreateView):
    model = Membership
    fields = ['location', 'start_date', 'end_date', 'image']
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    success_url='/home'

# LoginRequiredMixin has to be used with classes, @login_required will cause an error
class MembershipUpdate(LoginRequiredMixin, UpdateView):
    model = Membership
    fields = ['location', 'start_date', 'end_date']
    success_url='/home'


############################
# signup

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('home')
    else:
      error_message = 'Invalid credentials - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}

    <h1>About</h1>

    <div class="about-container">
        <div class="about-content">
            <h5>Our History</h5>
            <p>Fitness Factory was established in 2022. Our main goal is to provide suitable atmosphere for the ones that are training at our gym. Along with several classes that suit each persons schedule and requirements.</p>
            <p>Our trainers are Salwa, Noorah and Alex who have been working with us since we were established. They will provide all required assisstance during the training sessions.</p>
            <p>Classes vary depending on the season, but they usually run for one month each. You can register to the classes of your choice by clicking on the Classes tab and registering.</p>
            <p>Don't forget to create your membership card first!</p>
        </div>
        <div class="about-content-space"></div>
        <div class="about-contacts">
            <h5>Contact us</h5>
            <p>Phone: +973 3445682122</p>
            <p>Email: fitness-factory@gmail.com</p>
            <p>Locations:</p>
            <p>Muharraq Branch</p>
            <p>Seef Branch</p>
        </div>
    </div>
    

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Gym</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/fontawesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <!-- <ul>
          <li><a href="/home" class="left brand-logo">&nbsp;&nbsp;Fitness Factory&nbsp;&nbsp;</a></li>
        </ul> -->
        <ul class="right">
          <li><a href="/home">Home</a></li>
          <li><a href="/about">About</a></li>
          {% if user.is_authenticated %}
            <!-- {% if Membership.user_id != user.id %} -->
            <li><a href="{% url 'membership' user.id %}" class="navbar-membership">My Membership</a></li>
            <!-- {% else %}
              <li><a href="/membership/create">My Membership</a></li> -->
            <!-- {% endif %} -->
            <li><a href="/classes">Classes</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
          {% else %}
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/classes/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Classes List</h1>

{% for class in classes %}
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ class.name }}</span>
            <p>Location: {{ class.get_location_display }}</p>
            <p>Trainer: {{ class.trainer }}</p>
            <span>Every</span>
            {% for day in class.days %}
                <span> {{ day }}, </span>
            {% endfor %}
            <span>at {{ class.time }} for {{ class.duration }}</span>
            <p>Starting from {{ class.start_date }} to {{ class.end_date }}</p>
            <p>Available seats: {{ class.seats }}</p>
        </div>
        {% if class.seats > 0 %}
            <div class="card-action">
                <form action="{% url 'assoc_class' user.id class.id %}" method="post">
                    {% csrf_token %}
                <button type="submit" class="btn">Register</button>
                </form>
            </div>
        {% else %}
            <div class="card-action">
                <button class="btn" id="btn-class-full">Class Full</button>
            </div>
        {% endif %}
    </div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}

    <div class="home-container">
        <div class="home-content">
           <h1>Fitness Factory</h1>
            <p class="intro">Hard work beats talent when talent doesn't work hard</p> 
        </div>
        <div class="home-img">
            <img src="../static/images/threadmill.png">
        </div>
    </div>
    <div class="home-container2">
        <div class="home-content2">
            <p>In Fitness Factory we provide a wide range of classes with top trainers to guid you through your training.</p>
            <p>Explore our classes and register for the ones that you like with your favourite trainer.</p>
            <h3>Trainers</h3>
        </div>
        <div class="trainer-pic">
            <img src="../static/images/salwa.PNG">
            <h5>Salwa</h5>
        </div>
        <div class="trainer-pic">
            <img src="../static/images/noora.PNG">
            <h5>Noorah</h5>
        </div>
        <div class="trainer-pic">
            <img src="../static/images/alex.PNG">
            <h5>Alex</h5>
        </div>
    </div>
    

{% endblock %}

main_app/templates/main_app/membership_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h1>Edit <span class="teal-text">{{ object.user_code }}</span></h1>
{% else %}
    <h1>Add Membership</h1>
{% endif %}

<form action="" method="POST">
    <!-- the csrf is for security & it's required in django forms -->
    {% csrf_token %}

    <table>
        {{ form.as_table }}
    </table>

    <input type="submit" value="submit" class="btn">
</form>

<script>
    var dateEl = document.getElementById('id_end_date');
    var dateE2 = document.getElementById('id_start_date');
    M.Datepicker.init(dateEl, {
      format: 'yyyy-mm-dd',
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true
    });
    M.Datepicker.init(dateE2, {
      format: 'yyyy-mm-dd',
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true
    });
  
    var selectEl = document.getElementById('id_location');
    M.FormSelect.init(selectEl);
  
</script>

{% endblock %}

main_app/templates/membership/index.html
{% extends 'base.html' %}

{% block content %}

    <h1>Membership Details</h1>

    <div class="membership-card-container">
        <div class="membership-card-content">
            <h5>Membership Card</h5>
            <p>Name: {{ user.username }}</p>
            <p>Valid to use at {{ membership.get_location_display }} branch</p>
            <p>Starting from {{ membership.start_date }} until {{ membership.end_date }}</p>
        </div>
        
        <div class="card-action" id="membership-card-edit">
            <a href="{% url 'membership_update' user.id %}">Edit</a>
        </div>
    </div>


    {% for class in classes %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ class.name }}</span>
                <p>Location: {{ class.get_location_display }}</p>
                <p>Trainer: {{ class.trainer }}</p>
                <span>Every</span>
                {% for day in class.days %}
                    <span> {{ day }}, </span>
                {% endfor %}
                <span>at {{ class.time }} for {{ class.duration }}</span>
                <p>Starting from {{ class.start_date }} to {{ class.end_date }}</p>
                <p>Available seats: {{ class.seats }}</p>
            </div>
            <div class="card-action">
                <form action="{% url 'unassoc_class' user.id class.id %}" method="post">
                    {% csrf_token %}
                <button type="submit" class="btn">Remove</button>
                </form>
            </div>
        </div>
    {% endfor %}

{% endblock %}